apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    io.kompose.service: relay
  name: relay-ingress
spec:
  rules:
  - host: hellonode.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: relay
            port: 
              number: 3000